### ISSUE TITLE
Static binary release

### ISSUE THREAD

**Issue by jsixface** [cloudson/gitql#81]
To eliminate the dynamic dependency on libgit2 / git2go and do a static binary build on all three platforms - Linux/Mac/Windows.

**Comment by jsixface** [comment]
I looked into the possibility of making a static build, but that is kind of impossible since libigt2 has dependencies. 

> Note that even if libgit2 is included in the resulting binary, its dependencies will not be.

https://github.com/libgit2/git2go#master-branch-or-static-linking

The best I can think of is, to setup go module, include a versioned branch of git2go in go dependency and have libgit2, openSSL and LibSSH2 as separately installed dependency.

**Comment by cloudson** [comment]
Thanks for the research @jsixface . That's something that I don't know exactly how to solve keeping libgit2 as dependecny 😿. 
If you if find anything else please send it for us here.

**Comment by navigaid** [comment]
Hi, I stumbled upon this issue while researching how to build static binaries with git2go. After some trial and error, I think successfully solved the problem. Here is the final solution that I came up with

```
$ docker run -v $PWD:/go/bin --rm quay.io/git2go/static go get --tags static github.com/navigaid/gitql
$ file ./gitql 
./gitql: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

I made some changes go gitql in my fork, otherwise they won't build against the latest git2go, since it's api has changed a bit.

links:
- my fork of this project: https://github.com/navigaid/gitql
- Dockerfile for quay.io/git2go/static:  https://github.com/navigaid/docker-git2go-static-build

**Comment by cloudson** [comment]
Hey @navigaid , first of all thanks a lot for the effort. 
When gitql was cretead we didn't have go modules so the best way to make sure that git2go would not break the compiling was to fork it and point to `cloudson/git2go`. If you think that we need to upgrade cloudson/git2go, we can do that. 

Can you make a pull request with your gitql changes and the git2go upgrade?

**Comment by navigaid** [comment]
Hi @cloudson, 

I didn't make any change to `cloudson/git2go` in my fork of `cloudson/gitql`, instead it is replaced with master branch of `github.com/libgit2/git2go`, so there is no need to upgrade `cloudson/git2go`. 

Do we have plans to switch to go mod? If yes, then we can drop `cloudson/git2go` and use upstream `github.com/libgit2/git2go`. Current version of `cloudson/git2go` is way too old.

I'm not sure if the changes I've made in my fork will break the build on other platforms (MacOS and Windows). Is there any way to easily verify that? My plan is to add a Windows and MacOS builder in `.travis.yml`, so we can make sure I didn't break things by accident. 

I think we should solve the "go mod" and "travis ci" problems first. What do you think?

**Comment by cloudson** [comment]
The problem of use `github.com/libgit2/git2go` without go modules is that they can upgrade the 
lib breaking compatibility (it already happened before). That's why I'm in favor to keep cloudson/git2go until go modules support. 

So, for me, we could merge your changes of gitql + static compilation pointing to an upgraded cloudson/git2go.
After that we can move to go modules and remove cloudson/git2go. The intent is to have baby steps and smaller changes. What do you think?

**Comment by navigaid** [comment]
Sounds good to me. Let me adjust my code a little bit, and make sure it also works under Windows/macOS. It will probably take a few days before I make a pull request since I'm have other projects to take care of. So please be patient

**Comment by jsixface** [comment]
If breaking changes in upstream is a problem, we can go with a versioned branch in go module dependency. 
```
[[constraint]]
  branch = "v27"
  name = "gopkg.in/libgit2/git2go.v27"
```
I have a version that works with go module. But it is little lagging behind.
https://github.com/jsixface/gitql/tree/git2go

**Comment by cloudson** [comment]
@jsixface we have now static binaries for windows and linux so I'm going to close this. For macos it something that we need to improve but we also need to track if most of the users use mac and require this.

**Comment by jsixface** [comment]
What is the issue with static binary for MacOS. I can give it a try.

**Comment by cloudson** [comment]
When I tried throught github actions, it happened something like this 
https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag
